# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(533, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setGeometry(QtCore.QRect(10, 10, 521, 591))
        self.mainWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(53, 54, 58);\n"
"    border-radius: 50px;\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.statusBarFrame = QtWidgets.QFrame(self.mainWidget)
        self.statusBarFrame.setGeometry(QtCore.QRect(0, 0, 521, 41))
        self.statusBarFrame.setStyleSheet("QFrame{\n"
"    border: 2px solid rgb(255,0,255);\n"
"    background-color: rgb(47,54,79);\n"
"    border-radius: 12px;\n"
"}")
        self.statusBarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusBarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusBarFrame.setObjectName("statusBarFrame")
        self.iconLabel = QtWidgets.QLabel(self.statusBarFrame)
        self.iconLabel.setGeometry(QtCore.QRect(18, 5, 31, 31))
        self.iconLabel.setStyleSheet("border:rgb(47,79,79);")
        self.iconLabel.setText("")
        self.iconLabel.setPixmap(QtGui.QPixmap(":/icons/twitch_icon.ico"))
        self.iconLabel.setScaledContents(True)
        self.iconLabel.setObjectName("iconLabel")
        self.subLabel = QtWidgets.QLabel(self.statusBarFrame)
        self.subLabel.setGeometry(QtCore.QRect(60, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.subLabel.setFont(font)
        self.subLabel.setStyleSheet("border:rgb(47,79,79);\n"
"color: rgb(255,0,255);")
        self.subLabel.setObjectName("subLabel")
        self.closePushButton = QtWidgets.QPushButton(self.statusBarFrame)
        self.closePushButton.setGeometry(QtCore.QRect(454, 7, 61, 28))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.closePushButton.setFont(font)
        self.closePushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 12px;\n"
"    background-color: rgb(138,43,226);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,43,255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47,54,79);\n"
"    color: rgb(255,43,255);\n"
"}")
        self.closePushButton.setObjectName("closePushButton")
        self.minimizePushButton = QtWidgets.QPushButton(self.statusBarFrame)
        self.minimizePushButton.setGeometry(QtCore.QRect(388, 7, 61, 28))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.minimizePushButton.setFont(font)
        self.minimizePushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 12px;\n"
"    background-color: rgb(138,43,226);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,43,255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47,54,79);\n"
"    color: rgb(255,43,255);\n"
"}")
        self.minimizePushButton.setObjectName("minimizePushButton")
        self.label_7 = QtWidgets.QLabel(self.statusBarFrame)
        self.label_7.setGeometry(QtCore.QRect(15, 5, 31, 31))
        self.label_7.setStyleSheet("border: rgb(53, 54, 58);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/prfx/twitch_icon.ico"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.send_message_entry = QtWidgets.QLineEdit(self.mainWidget)
        self.send_message_entry.setGeometry(QtCore.QRect(40, 506, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.send_message_entry.setFont(font)
        self.send_message_entry.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(138,43,226);\n"
"    border-top-left-radius :20px;\n"
"    border-bottom-right-radius : 20px;\n"
"    color: rgb(138,43,226);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(138,43,226);\n"
"}\n"
"    /*border-top-left-radius :20px;*/\n"
"    /*border-bottom-right-radius : 20px;*/\n"
"")
        self.send_message_entry.setText("")
        self.send_message_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.send_message_entry.setObjectName("send_message_entry")
        self.send_message_button = QtWidgets.QPushButton(self.mainWidget)
        self.send_message_button.setGeometry(QtCore.QRect(270, 506, 231, 61))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        self.send_message_button.setFont(font)
        self.send_message_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_message_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(138,43,226);\n"
"    color: rgb(255,0,255);\n"
"    border-top-left-radius :5px;\n"
"    border-bottom-right-radius : 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,43,255);\n"
"    color: rgb(138,43,226);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(47,54,79);\n"
"    color: rgb(255,43,255);\n"
"}")
        self.send_message_button.setObjectName("send_message_button")
        self.scrollArea = QtWidgets.QScrollArea(self.mainWidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 50, 501, 441))
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border-radius: 3px;\n"
"    border: 1px solid  rgb(255,43,255);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(45, 45, 68);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(80, 80, 122);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(59, 59, 90);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.subLabel.setText(_translate("MainWindow", "Chat Bot for You"))
        self.closePushButton.setText(_translate("MainWindow", "X"))
        self.minimizePushButton.setText(_translate("MainWindow", "_"))
        self.send_message_entry.setPlaceholderText(_translate("MainWindow", "message"))
        self.send_message_button.setText(_translate("MainWindow", "Send"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
import asets_rc
import resource_rc
